only install conda when needed

diff --git a/build b/build
--- a/build
+++ b/build
@@ -2,27 +2,33 @@
 
 GREEN='\033[0;32m'
 NC='\033[0m' # No Color
-echo -e ${GREEN}Downloading and installing Anaconda...${NC}
-hash wget 2>/dev/null || { echo >&2 "This process requires wget but it's not installed."; read -p "Press ENTER to abort"; echo "Aborting."; exit 1; }
-ANACONDA=Anaconda3-2023.07-2-Linux-x86_64.sh
-wget https://repo.anaconda.com/archive/$ANACONDA
-prefix=""
-if [[ $(hostname -f) != *"uni-saarland.de" ]]; then
-    read -ep $'Anaconda3 will now be installed into this location:\n${HOME}/anaconda3\n\nPress enter to confirm or specify another location: ' prefix
-    if [ $prefix != $'\n' ]; then 
-        bash $ANACONDA -bp $prefix
+
+install_conda() {
+    echo -e ${GREEN}Downloading and installing Anaconda...${NC}
+    hash wget 2>/dev/null || { echo >&2 "This process requires wget but it's not installed."; read -p "Press ENTER to abort"; echo "Aborting."; exit 1; }
+    ANACONDA=Anaconda3-2023.07-2-Linux-x86_64.sh
+    wget https://repo.anaconda.com/archive/$ANACONDA
+    prefix=""
+    if [[ $(hostname -f) != *"uni-saarland.de" ]]; then
+        read -ep $'Anaconda3 will now be installed into this location:\n${HOME}/anaconda3\n\nPress enter to confirm or specify another location: ' prefix
+        if [ $prefix != $'\n' ]; then 
+            bash $ANACONDA -bp $prefix
+        else
+            bash $ANACONDA -b
+        fi
     else
-        bash $ANACONDA -b
+        echo -e ${GREEN}host is uni.saarland.de, installing Anaconda3 in /local/$USER/anaconda3${NC}
+        bash $ANACONDA -bp /local/$USER/anaconda3
+        prefix="/local/$USER/anaconda3"
     fi
-else
-    echo -e ${GREEN}host is uni.saarland.de, installing Anaconda3 in /local/$USER/anaconda3${NC}
-    bash $ANACONDA -bp /local/$USER/anaconda3
-    prefix="/local/$USER/anaconda3"
-fi
-rm -f $ANACONDA
-printf "\n# Anaconda3 path\nexport PATH=$prefix/bin:$PATH\n" >> $HOME/.bashrc
-conda init
-source ~/.bashrc 
+    rm -f $ANACONDA
+    printf "\n# Anaconda3 path\nexport PATH=$prefix/bin:$PATH\n" >> $HOME/.bashrc
+    conda init
+    source ~/.bashrc
+}
+
+hash conda 2>/dev/null || install_conda
+
 echo -e ${GREEN}Looking for Anaconda3 updates...${NC}
 conda update conda -y
 echo -e ${GREEN}Creating anaconda environment "dl-in-dh"...${NC}
